version: 2

sources : 

  - name: local_bike
    schema: local_bike
    tables:
      - name: brands_BG
      - name: categories_BG
      - name: customers_BG
      - name: order_items_BG
      - name: orders_BG
      - name: products_BG
      - name: staffs_BG
      - name: stocks_BG
      - name: stores_BG


